#ifndef USB_NOTIFY_SERVICE_01_H
#define USB_NOTIFY_SERVICE_01_H
/**
  @file usb_notify_v01.h

  @brief This is the public header file which defines the usb_notify service Data structures.

  This header file defines the types and structures that were defined in
  usb_notify. It contains the constant values defined, enums, structures,
  messages, and service message IDs (in that order) Structures that were
  defined in the IDL as messages contain mandatory elements, optional
  elements, a combination of mandatory and optional elements (mandatory
  always come before optionals in the structure), or nothing (null message)

  An optional element in a message is preceded by a uint8_t value that must be
  set to true if the element is going to be included. When decoding a received
  message, the uint8_t values will be set to true or false by the decode
  routine, and should be checked before accessing the values that they
  correspond to.

  Variable sized arrays are defined as static sized arrays with an unsigned
  integer (32 bit) preceding it that must be set to the number of elements
  in the array that are valid. For Example:

  uint32_t test_opaque_len;
  uint8_t test_opaque[16];

  If only 4 elements are added to test_opaque[] then test_opaque_len must be
  set to 4 before sending the message.  When decoding, the _len value is set
  by the decode routine and should be checked so that the correct number of
  elements in the array will be accessed.

*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
  

  
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*
 *THIS IS AN AUTO GENERATED FILE. DO NOT ALTER IN ANY WAY
 *====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/

/* This file was generated with Tool version 6.14.9 
   It was generated on: Fri Feb  2 2018 (Spin 0)
   From IDL File: usb_notify_v01.idl */

/** @defgroup usb_notify_qmi_consts Constant values defined in the IDL */
/** @defgroup usb_notify_qmi_msg_ids Constant values for QMI message IDs */
/** @defgroup usb_notify_qmi_enums Enumerated types used in QMI messages */
/** @defgroup usb_notify_qmi_messages Structures sent as QMI messages */
/** @defgroup usb_notify_qmi_aggregates Aggregate types used in QMI messages */
/** @defgroup usb_notify_qmi_accessor Accessor for QMI service object */
/** @defgroup usb_notify_qmi_version Constant values for versioning information */

#include <stdint.h>
#include "qmi_idl_lib.h"


#ifdef __cplusplus
extern "C" {
#endif

/** @addtogroup usb_notify_qmi_version
    @{
  */
/** Major Version Number of the IDL used to generate this file */
#define USB_NOTIFY_V01_IDL_MAJOR_VERS 0x01
/** Revision Number of the IDL used to generate this file */
#define USB_NOTIFY_V01_IDL_MINOR_VERS 0x01
/** Major Version Number of the qmi_idl_compiler used to generate this file */
#define USB_NOTIFY_V01_IDL_TOOL_VERS 0x06
/** Maximum Defined Message ID */
#define USB_NOTIFY_V01_MAX_MESSAGE_ID 0x0001
/**
    @}
  */

/** @addtogroup usb_notify_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {

  /* Mandatory */
  uint8_t state;
}usb_state_req_msg_v01;  /* Message */
/**
    @}
  */

/** @addtogroup usb_notify_qmi_messages
    @{
  */
/**  Message;  */
typedef struct {

  /* Mandatory */
  uint8_t result;
}usb_state_resp_msg_v01;  /* Message */
/**
    @}
  */

/* Conditional compilation tags for message removal */ 

/*Service Message Definition*/
/** @addtogroup usb_notify_qmi_msg_ids
    @{
  */
#define QMI_USB_STATE_REQ_V01 0x0001
#define QMI_USB_STATE_RESP_V01 0x0001
/**
    @}
  */

/* Service Object Accessor */
/** @addtogroup wms_qmi_accessor
    @{
  */
/** This function is used internally by the autogenerated code.  Clients should use the
   macro usb_notify_get_service_object_v01( ) that takes in no arguments. */
qmi_idl_service_object_type usb_notify_get_service_object_internal_v01
 ( int32_t idl_maj_version, int32_t idl_min_version, int32_t library_version );

/** This macro should be used to get the service object */
#define usb_notify_get_service_object_v01( ) \
          usb_notify_get_service_object_internal_v01( \
            USB_NOTIFY_V01_IDL_MAJOR_VERS, USB_NOTIFY_V01_IDL_MINOR_VERS, \
            USB_NOTIFY_V01_IDL_TOOL_VERS )
/**
    @}
  */


#ifdef __cplusplus
}
#endif
#endif

